version: "3.8"

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: "strapi-practice-db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db/pgsql-data:/var/lib/postgresql/data
  app:
    image: node:16.13.1
    ports:
      - "8080:8080"
      - "1337:1337"
    volumes:
      - ./app:/src
    working_dir: /src/strapi-practice
    tty: true
    depends_on:
      - postgres
    command: yarn develop
